In [8]:
##                NUMPY
# We use numpy to perform the operation with arra and matrix
# random.randn is the syntax of numpy for generating random number

import numpy as np
data = np.random.randn(2,3) # generates a random matrix of 2x3

print(data,"\n")

print(data + data,"\n") # adds matrix to itself

print(data*10,"\n")

print(data.shape,"\n") # defines the row and column in matrix

print(data.dtype,"\n") # dfeines the data type of data

print(data.ndim,"\n") # defines the dimension of the data(how many arrays are in it)

[[-0.05688718  0.57534888  0.79699612]
 [ 0.49597177  1.02343017  1.00516638]] 

[[-0.11377437  1.15069776  1.59399224]
 [ 0.99194354  2.04686034  2.01033276]] 

[[-0.56887183  5.7534888   7.96996122]
 [ 4.95971772 10.23430169 10.05166378]] 

(2, 3) 

float64 

2 



In [18]:
print(np.zeros(10),"\n") # prints a array of 10 zeroes

print(np.zeros((3,6)),"\n") # prints a 3x6 matrix of zeros

print(np.zeros((2,3,6)),"\n") # prints 2 matrix of 3x6

# the elemets of empty and zero matrix are zeros but sometimes empty matrix shows garbage value at any place of matrix
print("it is empty matrix\n",np.empty((3,6)),"\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] 

it is empty matrix
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 



In [48]:
#              SOME NUMPY OPERATIONS

arr = np.array([4,2,6,8] ,dtype='int64') # converting a normal array into numpy array
print(arr.astype(np.float64)) # astype use to change the data type

print("Normal Array",arr,"\n")

print("Addition with Array",arr+arr,"\n")

print("Multiplication with Array",arr*2,"\n")

print("Division with Array",arr/2,"\n")

print("Power of Array",arr**2,"\n")

print("Square root of Array",np.sqrt(arr),"\n")

print("Exponent of Array",np.exp(arr),"\n")

print("Sorting an Array",np.sort(arr),"\n")

# some statistic operation
print("Mean of Array",np.mean(arr),"\n")

print("Sum of Array",np.sum(arr),"\n")

print("cumsum of Array",np.cumsum(arr),"\n") # addition of each trailing element

# Boolean opeation
arr2=np.array([0,1,3,5])
print(arr>arr2,"\n") #compares each element of both arrays
print(arr<arr2)

[4. 2. 6. 8.]
Normal Array [4 2 6 8] 

Addition with Array [ 8  4 12 16] 

Multiplication with Array [ 8  4 12 16] 

Division with Array [2. 1. 3. 4.] 

Power of Array [16  4 36 64] 

Square root of Array [2.         1.41421356 2.44948974 2.82842712] 

Exponent of Array [  54.59815003    7.3890561   403.42879349 2980.95798704] 

Sorting an Array [2 4 6 8] 

Mean of Array 5.0 

Sum of Array 20 

cumsum of Array [ 4  6 12 20] 

[ True  True  True  True] 

[False False False False]


In [50]:
##                  RANGE IN NUMPY
# .arange is the sytax of range in numpy

arr = np.arange(10)
print(arr)

arr2 = arr[4:8]
print(arr2)

arr[4:8]=0
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7]
[0 1 2 3 0 0 0 0 8 9]


In [40]:
namesArr = np.array(["Umair","Noman","Tlaha","Salman","Noman"])
numArr  = np.random.randn(5,3)

print(namesArr,"\n")
print(numArr,"\n")
print(namesArr=="Noman","\n")
print(numArr[namesArr=="Noman"],"\n") # print the rows where noman is true(only prints 2nd and last rows)
print(numArr[~(namesArr=="Noman")],"\n") # prints all the false rows
print(np.unique(namesArr),"\n") # neglects the multiple elements and only type each element once, also sorts the element

['Umair' 'Noman' 'Tlaha' 'Salman' 'Noman'] 

[[-2.2287274   1.87281542 -0.03932771]
 [-0.50709218  1.14963584  0.56449658]
 [ 0.12998018  0.1812051  -0.52749813]
 [ 0.85255497  1.16886307  0.48649305]
 [-0.44283265  0.26313543 -0.36727667]] 

[False  True False False  True] 

[[-0.50709218  1.14963584  0.56449658]
 [-0.44283265  0.26313543 -0.36727667]] 

[[-2.2287274   1.87281542 -0.03932771]
 [ 0.12998018  0.1812051  -0.52749813]
 [ 0.85255497  1.16886307  0.48649305]] 

['Noman' 'Salman' 'Tlaha' 'Umair'] 



In [47]:
arr = np.random.randn(5)
print(arr,"\n")

arr2 = np.random.randn(5)
print(arr2,"\n")

print("Maximum Array", np.maximum(arr,arr2),"\n")  # compares each elemets of both arrays and make a single array of maximum values of both arrays
print("Minimum Array" ,np.minimum(arr,arr2))  # compares each elemets of both arrays and make a single array of minimum values of both arrays


[0.20028582 0.24999497 1.02853197 1.49405966 1.0653947 ] 

[0.22533911 1.22253329 1.50097344 0.50766755 1.02336786] 

Maximum Array [0.22533911 1.22253329 1.50097344 1.49405966 1.0653947 ] 

Minimum Array [0.20028582 0.24999497 1.02853197 0.50766755 1.02336786]
